"""empty message

Revision ID: 12dc81530af6
Revises: df1bd385d418
Create Date: 2023-06-04 06:40:41.122799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dc81530af6'
down_revision = 'df1bd385d418'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
