"""empty message

Revision ID: 16fa410dc522
Revises: 12dc81530af6
Create Date: 2023-06-04 06:41:11.998153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fa410dc522'
down_revision = '12dc81530af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('seller_profile_image', sa.String(), nullable=True))
    op.drop_column('seller', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('seller', 'seller_profile_image')
    # ### end Alembic commands ###
