"""empty message

Revision ID: 17cb71813849
Revises: eccca0ec2a3b
Create Date: 2023-06-05 01:23:47.352344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cb71813849'
down_revision = 'eccca0ec2a3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('market_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market', 'market_type')
    # ### end Alembic commands ###
