"""empty message

Revision ID: 183502b1acfe
Revises: 6db2e9e47328
Create Date: 2023-06-04 03:42:23.852712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183502b1acfe'
down_revision = '6db2e9e47328'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
