"""empty message

Revision ID: 43d5341f31a3
Revises: f202607e5b8c
Create Date: 2023-06-14 22:09:07.471110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d5341f31a3'
down_revision = 'f202607e5b8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
