"""empty message

Revision ID: 6143f2e52e81
Revises: 16fa410dc522
Create Date: 2023-06-04 06:42:48.566122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6143f2e52e81'
down_revision = '16fa410dc522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
