"""empty message

Revision ID: 6db2e9e47328
Revises: 1513f36caedd
Create Date: 2023-06-04 03:30:21.433521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db2e9e47328'
down_revision = '1513f36caedd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('parking_lot', sa.Boolean(), nullable=False),
    sa.Column('toilet', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flee_market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('popup_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('parking_lot', sa.Boolean(), nullable=False),
    sa.Column('toilet', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('market_name_key', 'market', type_='unique')
    op.drop_constraint('seller_seller_name_key', 'seller', type_='unique')
    op.drop_constraint('user_account_key', 'user', type_='unique')
    op.drop_constraint('user_nickname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_nickname_key', 'user', ['nickname'])
    op.create_unique_constraint('user_account_key', 'user', ['account'])
    op.create_unique_constraint('seller_seller_name_key', 'seller', ['seller_name'])
    op.create_unique_constraint('market_name_key', 'market', ['name'])
    op.drop_table('popup_store')
    op.drop_table('flee_market')
    op.drop_table('event')
    # ### end Alembic commands ###
