"""empty message

Revision ID: 8347df81fc34
Revises: a2b0960aebd4
Create Date: 2023-06-14 21:30:55.171963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8347df81fc34'
down_revision = 'a2b0960aebd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('market', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('market', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('market', 'updated_at')
    op.drop_column('market', 'created_at')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    # ### end Alembic commands ###
