"""empty message

Revision ID: a2b0960aebd4
Revises: fd0edd92e98d
Create Date: 2023-06-14 21:20:57.015009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b0960aebd4'
down_revision = 'fd0edd92e98d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_market_id'), 'market', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_market_id'), table_name='market')
    # ### end Alembic commands ###
