"""empty message

Revision ID: eccca0ec2a3b
Revises: 6143f2e52e81
Create Date: 2023-06-04 06:44:52.928009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccca0ec2a3b'
down_revision = '6143f2e52e81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
