"""empty message

Revision ID: fd0edd92e98d
Revises: 17cb71813849
Create Date: 2023-06-05 01:26:29.894787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0edd92e98d'
down_revision = '17cb71813849'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
